Fix bug in git lfs pre-push hook

diff --git a/git/hooks/pre-push.d/lfs b/git/hooks/pre-push.d/lfs
--- a/git/hooks/pre-push.d/lfs
+++ b/git/hooks/pre-push.d/lfs
@@ -1,3 +1,18 @@
 #!/bin/sh
-command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/pre-push'.\n"; exit 2; }
+
+if [ ! -e .gitattributes ]; then
+    # This repository not configured for Git LFS.
+    exit 0
+fi
+
+if ! grep -Ev '\s*#' .gitattributes | grep -q 'filter=lfs'; then
+    # This repository not configured for Git LFS.
+    exit 0
+fi
+
+if ! command -v git-lfs >/dev/null 2>&1 ; then
+    echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/pre-push'.\n"
+    exit 2
+fi
+
 git lfs pre-push "$@"
